package com.salk.salkdemo.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class ExportExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table export
	 * @mbggenerated
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table export
	 * @mbggenerated
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table export
	 * @mbggenerated
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table export
	 * @mbggenerated
	 */
	public ExportExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table export
	 * @mbggenerated
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table export
	 * @mbggenerated
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table export
	 * @mbggenerated
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table export
	 * @mbggenerated
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table export
	 * @mbggenerated
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table export
	 * @mbggenerated
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table export
	 * @mbggenerated
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table export
	 * @mbggenerated
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table export
	 * @mbggenerated
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table export
	 * @mbggenerated
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table export
	 * @mbggenerated
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		protected void addCriterionForJDBCDate(String condition, Date value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value.getTime()),
					property);
		}

		protected void addCriterionForJDBCDate(String condition,
				List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				dateList.add(new java.sql.Date(iter.next().getTime()));
			}
			addCriterion(condition, dateList, property);
		}

		protected void addCriterionForJDBCDate(String condition, Date value1,
				Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			addCriterion(condition, new java.sql.Date(value1.getTime()),
					new java.sql.Date(value2.getTime()), property);
		}

		protected void addCriterionForJDBCTime(String condition, Date value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			addCriterion(condition, new java.sql.Time(value.getTime()),
					property);
		}

		protected void addCriterionForJDBCTime(String condition,
				List<Date> values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property
						+ " cannot be null or empty");
			}
			List<java.sql.Time> timeList = new ArrayList<java.sql.Time>();
			Iterator<Date> iter = values.iterator();
			while (iter.hasNext()) {
				timeList.add(new java.sql.Time(iter.next().getTime()));
			}
			addCriterion(condition, timeList, property);
		}

		protected void addCriterionForJDBCTime(String condition, Date value1,
				Date value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			addCriterion(condition, new java.sql.Time(value1.getTime()),
					new java.sql.Time(value2.getTime()), property);
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andExportNoIsNull() {
			addCriterion("export_no is null");
			return (Criteria) this;
		}

		public Criteria andExportNoIsNotNull() {
			addCriterion("export_no is not null");
			return (Criteria) this;
		}

		public Criteria andExportNoEqualTo(String value) {
			addCriterion("export_no =", value, "exportNo");
			return (Criteria) this;
		}

		public Criteria andExportNoNotEqualTo(String value) {
			addCriterion("export_no <>", value, "exportNo");
			return (Criteria) this;
		}

		public Criteria andExportNoGreaterThan(String value) {
			addCriterion("export_no >", value, "exportNo");
			return (Criteria) this;
		}

		public Criteria andExportNoGreaterThanOrEqualTo(String value) {
			addCriterion("export_no >=", value, "exportNo");
			return (Criteria) this;
		}

		public Criteria andExportNoLessThan(String value) {
			addCriterion("export_no <", value, "exportNo");
			return (Criteria) this;
		}

		public Criteria andExportNoLessThanOrEqualTo(String value) {
			addCriterion("export_no <=", value, "exportNo");
			return (Criteria) this;
		}

		public Criteria andExportNoLike(String value) {
			addCriterion("export_no like", value, "exportNo");
			return (Criteria) this;
		}

		public Criteria andExportNoNotLike(String value) {
			addCriterion("export_no not like", value, "exportNo");
			return (Criteria) this;
		}

		public Criteria andExportNoIn(List<String> values) {
			addCriterion("export_no in", values, "exportNo");
			return (Criteria) this;
		}

		public Criteria andExportNoNotIn(List<String> values) {
			addCriterion("export_no not in", values, "exportNo");
			return (Criteria) this;
		}

		public Criteria andExportNoBetween(String value1, String value2) {
			addCriterion("export_no between", value1, value2, "exportNo");
			return (Criteria) this;
		}

		public Criteria andExportNoNotBetween(String value1, String value2) {
			addCriterion("export_no not between", value1, value2, "exportNo");
			return (Criteria) this;
		}

		public Criteria andExportSizeIsNull() {
			addCriterion("export_size is null");
			return (Criteria) this;
		}

		public Criteria andExportSizeIsNotNull() {
			addCriterion("export_size is not null");
			return (Criteria) this;
		}

		public Criteria andExportSizeEqualTo(String value) {
			addCriterion("export_size =", value, "exportSize");
			return (Criteria) this;
		}

		public Criteria andExportSizeNotEqualTo(String value) {
			addCriterion("export_size <>", value, "exportSize");
			return (Criteria) this;
		}

		public Criteria andExportSizeGreaterThan(String value) {
			addCriterion("export_size >", value, "exportSize");
			return (Criteria) this;
		}

		public Criteria andExportSizeGreaterThanOrEqualTo(String value) {
			addCriterion("export_size >=", value, "exportSize");
			return (Criteria) this;
		}

		public Criteria andExportSizeLessThan(String value) {
			addCriterion("export_size <", value, "exportSize");
			return (Criteria) this;
		}

		public Criteria andExportSizeLessThanOrEqualTo(String value) {
			addCriterion("export_size <=", value, "exportSize");
			return (Criteria) this;
		}

		public Criteria andExportSizeLike(String value) {
			addCriterion("export_size like", value, "exportSize");
			return (Criteria) this;
		}

		public Criteria andExportSizeNotLike(String value) {
			addCriterion("export_size not like", value, "exportSize");
			return (Criteria) this;
		}

		public Criteria andExportSizeIn(List<String> values) {
			addCriterion("export_size in", values, "exportSize");
			return (Criteria) this;
		}

		public Criteria andExportSizeNotIn(List<String> values) {
			addCriterion("export_size not in", values, "exportSize");
			return (Criteria) this;
		}

		public Criteria andExportSizeBetween(String value1, String value2) {
			addCriterion("export_size between", value1, value2, "exportSize");
			return (Criteria) this;
		}

		public Criteria andExportSizeNotBetween(String value1, String value2) {
			addCriterion("export_size not between", value1, value2,
					"exportSize");
			return (Criteria) this;
		}

		public Criteria andExportDateIsNull() {
			addCriterion("export_date is null");
			return (Criteria) this;
		}

		public Criteria andExportDateIsNotNull() {
			addCriterion("export_date is not null");
			return (Criteria) this;
		}

		public Criteria andExportDateEqualTo(Date value) {
			addCriterionForJDBCDate("export_date =", value, "exportDate");
			return (Criteria) this;
		}

		public Criteria andExportDateNotEqualTo(Date value) {
			addCriterionForJDBCDate("export_date <>", value, "exportDate");
			return (Criteria) this;
		}

		public Criteria andExportDateGreaterThan(Date value) {
			addCriterionForJDBCDate("export_date >", value, "exportDate");
			return (Criteria) this;
		}

		public Criteria andExportDateGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("export_date >=", value, "exportDate");
			return (Criteria) this;
		}

		public Criteria andExportDateLessThan(Date value) {
			addCriterionForJDBCDate("export_date <", value, "exportDate");
			return (Criteria) this;
		}

		public Criteria andExportDateLessThanOrEqualTo(Date value) {
			addCriterionForJDBCDate("export_date <=", value, "exportDate");
			return (Criteria) this;
		}

		public Criteria andExportDateIn(List<Date> values) {
			addCriterionForJDBCDate("export_date in", values, "exportDate");
			return (Criteria) this;
		}

		public Criteria andExportDateNotIn(List<Date> values) {
			addCriterionForJDBCDate("export_date not in", values, "exportDate");
			return (Criteria) this;
		}

		public Criteria andExportDateBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("export_date between", value1, value2,
					"exportDate");
			return (Criteria) this;
		}

		public Criteria andExportDateNotBetween(Date value1, Date value2) {
			addCriterionForJDBCDate("export_date not between", value1, value2,
					"exportDate");
			return (Criteria) this;
		}

		public Criteria andExportTypeIsNull() {
			addCriterion("export_type is null");
			return (Criteria) this;
		}

		public Criteria andExportTypeIsNotNull() {
			addCriterion("export_type is not null");
			return (Criteria) this;
		}

		public Criteria andExportTypeEqualTo(String value) {
			addCriterion("export_type =", value, "exportType");
			return (Criteria) this;
		}

		public Criteria andExportTypeNotEqualTo(String value) {
			addCriterion("export_type <>", value, "exportType");
			return (Criteria) this;
		}

		public Criteria andExportTypeGreaterThan(String value) {
			addCriterion("export_type >", value, "exportType");
			return (Criteria) this;
		}

		public Criteria andExportTypeGreaterThanOrEqualTo(String value) {
			addCriterion("export_type >=", value, "exportType");
			return (Criteria) this;
		}

		public Criteria andExportTypeLessThan(String value) {
			addCriterion("export_type <", value, "exportType");
			return (Criteria) this;
		}

		public Criteria andExportTypeLessThanOrEqualTo(String value) {
			addCriterion("export_type <=", value, "exportType");
			return (Criteria) this;
		}

		public Criteria andExportTypeLike(String value) {
			addCriterion("export_type like", value, "exportType");
			return (Criteria) this;
		}

		public Criteria andExportTypeNotLike(String value) {
			addCriterion("export_type not like", value, "exportType");
			return (Criteria) this;
		}

		public Criteria andExportTypeIn(List<String> values) {
			addCriterion("export_type in", values, "exportType");
			return (Criteria) this;
		}

		public Criteria andExportTypeNotIn(List<String> values) {
			addCriterion("export_type not in", values, "exportType");
			return (Criteria) this;
		}

		public Criteria andExportTypeBetween(String value1, String value2) {
			addCriterion("export_type between", value1, value2, "exportType");
			return (Criteria) this;
		}

		public Criteria andExportTypeNotBetween(String value1, String value2) {
			addCriterion("export_type not between", value1, value2,
					"exportType");
			return (Criteria) this;
		}

		public Criteria andRemarkIsNull() {
			addCriterion("remark is null");
			return (Criteria) this;
		}

		public Criteria andRemarkIsNotNull() {
			addCriterion("remark is not null");
			return (Criteria) this;
		}

		public Criteria andRemarkEqualTo(String value) {
			addCriterion("remark =", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotEqualTo(String value) {
			addCriterion("remark <>", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkGreaterThan(String value) {
			addCriterion("remark >", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkGreaterThanOrEqualTo(String value) {
			addCriterion("remark >=", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLessThan(String value) {
			addCriterion("remark <", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLessThanOrEqualTo(String value) {
			addCriterion("remark <=", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLike(String value) {
			addCriterion("remark like", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotLike(String value) {
			addCriterion("remark not like", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkIn(List<String> values) {
			addCriterion("remark in", values, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotIn(List<String> values) {
			addCriterion("remark not in", values, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkBetween(String value1, String value2) {
			addCriterion("remark between", value1, value2, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotBetween(String value1, String value2) {
			addCriterion("remark not between", value1, value2, "remark");
			return (Criteria) this;
		}

		public Criteria andExportColorIsNull() {
			addCriterion("export_color is null");
			return (Criteria) this;
		}

		public Criteria andExportColorIsNotNull() {
			addCriterion("export_color is not null");
			return (Criteria) this;
		}

		public Criteria andExportColorEqualTo(String value) {
			addCriterion("export_color =", value, "exportColor");
			return (Criteria) this;
		}

		public Criteria andExportColorNotEqualTo(String value) {
			addCriterion("export_color <>", value, "exportColor");
			return (Criteria) this;
		}

		public Criteria andExportColorGreaterThan(String value) {
			addCriterion("export_color >", value, "exportColor");
			return (Criteria) this;
		}

		public Criteria andExportColorGreaterThanOrEqualTo(String value) {
			addCriterion("export_color >=", value, "exportColor");
			return (Criteria) this;
		}

		public Criteria andExportColorLessThan(String value) {
			addCriterion("export_color <", value, "exportColor");
			return (Criteria) this;
		}

		public Criteria andExportColorLessThanOrEqualTo(String value) {
			addCriterion("export_color <=", value, "exportColor");
			return (Criteria) this;
		}

		public Criteria andExportColorLike(String value) {
			addCriterion("export_color like", value, "exportColor");
			return (Criteria) this;
		}

		public Criteria andExportColorNotLike(String value) {
			addCriterion("export_color not like", value, "exportColor");
			return (Criteria) this;
		}

		public Criteria andExportColorIn(List<String> values) {
			addCriterion("export_color in", values, "exportColor");
			return (Criteria) this;
		}

		public Criteria andExportColorNotIn(List<String> values) {
			addCriterion("export_color not in", values, "exportColor");
			return (Criteria) this;
		}

		public Criteria andExportColorBetween(String value1, String value2) {
			addCriterion("export_color between", value1, value2, "exportColor");
			return (Criteria) this;
		}

		public Criteria andExportColorNotBetween(String value1, String value2) {
			addCriterion("export_color not between", value1, value2,
					"exportColor");
			return (Criteria) this;
		}

		public Criteria andAdderNameIsNull() {
			addCriterion("adder_name is null");
			return (Criteria) this;
		}

		public Criteria andAdderNameIsNotNull() {
			addCriterion("adder_name is not null");
			return (Criteria) this;
		}

		public Criteria andAdderNameEqualTo(String value) {
			addCriterion("adder_name =", value, "adderName");
			return (Criteria) this;
		}

		public Criteria andAdderNameNotEqualTo(String value) {
			addCriterion("adder_name <>", value, "adderName");
			return (Criteria) this;
		}

		public Criteria andAdderNameGreaterThan(String value) {
			addCriterion("adder_name >", value, "adderName");
			return (Criteria) this;
		}

		public Criteria andAdderNameGreaterThanOrEqualTo(String value) {
			addCriterion("adder_name >=", value, "adderName");
			return (Criteria) this;
		}

		public Criteria andAdderNameLessThan(String value) {
			addCriterion("adder_name <", value, "adderName");
			return (Criteria) this;
		}

		public Criteria andAdderNameLessThanOrEqualTo(String value) {
			addCriterion("adder_name <=", value, "adderName");
			return (Criteria) this;
		}

		public Criteria andAdderNameLike(String value) {
			addCriterion("adder_name like", value, "adderName");
			return (Criteria) this;
		}

		public Criteria andAdderNameNotLike(String value) {
			addCriterion("adder_name not like", value, "adderName");
			return (Criteria) this;
		}

		public Criteria andAdderNameIn(List<String> values) {
			addCriterion("adder_name in", values, "adderName");
			return (Criteria) this;
		}

		public Criteria andAdderNameNotIn(List<String> values) {
			addCriterion("adder_name not in", values, "adderName");
			return (Criteria) this;
		}

		public Criteria andAdderNameBetween(String value1, String value2) {
			addCriterion("adder_name between", value1, value2, "adderName");
			return (Criteria) this;
		}

		public Criteria andAdderNameNotBetween(String value1, String value2) {
			addCriterion("adder_name not between", value1, value2, "adderName");
			return (Criteria) this;
		}

		public Criteria andAddTimeIsNull() {
			addCriterion("add_time is null");
			return (Criteria) this;
		}

		public Criteria andAddTimeIsNotNull() {
			addCriterion("add_time is not null");
			return (Criteria) this;
		}

		public Criteria andAddTimeEqualTo(Date value) {
			addCriterionForJDBCTime("add_time =", value, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeNotEqualTo(Date value) {
			addCriterionForJDBCTime("add_time <>", value, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeGreaterThan(Date value) {
			addCriterionForJDBCTime("add_time >", value, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCTime("add_time >=", value, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeLessThan(Date value) {
			addCriterionForJDBCTime("add_time <", value, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeLessThanOrEqualTo(Date value) {
			addCriterionForJDBCTime("add_time <=", value, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeIn(List<Date> values) {
			addCriterionForJDBCTime("add_time in", values, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeNotIn(List<Date> values) {
			addCriterionForJDBCTime("add_time not in", values, "addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeBetween(Date value1, Date value2) {
			addCriterionForJDBCTime("add_time between", value1, value2,
					"addTime");
			return (Criteria) this;
		}

		public Criteria andAddTimeNotBetween(Date value1, Date value2) {
			addCriterionForJDBCTime("add_time not between", value1, value2,
					"addTime");
			return (Criteria) this;
		}

		public Criteria andUpdaterNameIsNull() {
			addCriterion("updater_name is null");
			return (Criteria) this;
		}

		public Criteria andUpdaterNameIsNotNull() {
			addCriterion("updater_name is not null");
			return (Criteria) this;
		}

		public Criteria andUpdaterNameEqualTo(String value) {
			addCriterion("updater_name =", value, "updaterName");
			return (Criteria) this;
		}

		public Criteria andUpdaterNameNotEqualTo(String value) {
			addCriterion("updater_name <>", value, "updaterName");
			return (Criteria) this;
		}

		public Criteria andUpdaterNameGreaterThan(String value) {
			addCriterion("updater_name >", value, "updaterName");
			return (Criteria) this;
		}

		public Criteria andUpdaterNameGreaterThanOrEqualTo(String value) {
			addCriterion("updater_name >=", value, "updaterName");
			return (Criteria) this;
		}

		public Criteria andUpdaterNameLessThan(String value) {
			addCriterion("updater_name <", value, "updaterName");
			return (Criteria) this;
		}

		public Criteria andUpdaterNameLessThanOrEqualTo(String value) {
			addCriterion("updater_name <=", value, "updaterName");
			return (Criteria) this;
		}

		public Criteria andUpdaterNameLike(String value) {
			addCriterion("updater_name like", value, "updaterName");
			return (Criteria) this;
		}

		public Criteria andUpdaterNameNotLike(String value) {
			addCriterion("updater_name not like", value, "updaterName");
			return (Criteria) this;
		}

		public Criteria andUpdaterNameIn(List<String> values) {
			addCriterion("updater_name in", values, "updaterName");
			return (Criteria) this;
		}

		public Criteria andUpdaterNameNotIn(List<String> values) {
			addCriterion("updater_name not in", values, "updaterName");
			return (Criteria) this;
		}

		public Criteria andUpdaterNameBetween(String value1, String value2) {
			addCriterion("updater_name between", value1, value2, "updaterName");
			return (Criteria) this;
		}

		public Criteria andUpdaterNameNotBetween(String value1, String value2) {
			addCriterion("updater_name not between", value1, value2,
					"updaterName");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNull() {
			addCriterion("update_time is null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNotNull() {
			addCriterion("update_time is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeEqualTo(Date value) {
			addCriterionForJDBCTime("update_time =", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotEqualTo(Date value) {
			addCriterionForJDBCTime("update_time <>", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThan(Date value) {
			addCriterionForJDBCTime("update_time >", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
			addCriterionForJDBCTime("update_time >=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThan(Date value) {
			addCriterionForJDBCTime("update_time <", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
			addCriterionForJDBCTime("update_time <=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIn(List<Date> values) {
			addCriterionForJDBCTime("update_time in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotIn(List<Date> values) {
			addCriterionForJDBCTime("update_time not in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeBetween(Date value1, Date value2) {
			addCriterionForJDBCTime("update_time between", value1, value2,
					"updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
			addCriterionForJDBCTime("update_time not between", value1, value2,
					"updateTime");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table export
	 * @mbggenerated
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table export
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}