package com.salk.salkdemo.domain;

import java.util.Date;

public class Export {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column export.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column export.export_no
	 * @mbggenerated
	 */
	private String exportNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column export.export_size
	 * @mbggenerated
	 */
	private String exportSize;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column export.export_date
	 * @mbggenerated
	 */
	private Date exportDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column export.export_type
	 * @mbggenerated
	 */
	private String exportType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column export.remark
	 * @mbggenerated
	 */
	private String remark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column export.export_color
	 * @mbggenerated
	 */
	private String exportColor;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column export.adder_name
	 * @mbggenerated
	 */
	private String adderName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column export.add_time
	 * @mbggenerated
	 */
	private Date addTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column export.updater_name
	 * @mbggenerated
	 */
	private String updaterName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column export.update_time
	 * @mbggenerated
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column export.id
	 * @return  the value of export.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column export.id
	 * @param id  the value for export.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column export.export_no
	 * @return  the value of export.export_no
	 * @mbggenerated
	 */
	public String getExportNo() {
		return exportNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column export.export_no
	 * @param exportNo  the value for export.export_no
	 * @mbggenerated
	 */
	public void setExportNo(String exportNo) {
		this.exportNo = exportNo == null ? null : exportNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column export.export_size
	 * @return  the value of export.export_size
	 * @mbggenerated
	 */
	public String getExportSize() {
		return exportSize;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column export.export_size
	 * @param exportSize  the value for export.export_size
	 * @mbggenerated
	 */
	public void setExportSize(String exportSize) {
		this.exportSize = exportSize == null ? null : exportSize.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column export.export_date
	 * @return  the value of export.export_date
	 * @mbggenerated
	 */
	public Date getExportDate() {
		return exportDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column export.export_date
	 * @param exportDate  the value for export.export_date
	 * @mbggenerated
	 */
	public void setExportDate(Date exportDate) {
		this.exportDate = exportDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column export.export_type
	 * @return  the value of export.export_type
	 * @mbggenerated
	 */
	public String getExportType() {
		return exportType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column export.export_type
	 * @param exportType  the value for export.export_type
	 * @mbggenerated
	 */
	public void setExportType(String exportType) {
		this.exportType = exportType == null ? null : exportType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column export.remark
	 * @return  the value of export.remark
	 * @mbggenerated
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column export.remark
	 * @param remark  the value for export.remark
	 * @mbggenerated
	 */
	public void setRemark(String remark) {
		this.remark = remark == null ? null : remark.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column export.export_color
	 * @return  the value of export.export_color
	 * @mbggenerated
	 */
	public String getExportColor() {
		return exportColor;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column export.export_color
	 * @param exportColor  the value for export.export_color
	 * @mbggenerated
	 */
	public void setExportColor(String exportColor) {
		this.exportColor = exportColor == null ? null : exportColor.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column export.adder_name
	 * @return  the value of export.adder_name
	 * @mbggenerated
	 */
	public String getAdderName() {
		return adderName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column export.adder_name
	 * @param adderName  the value for export.adder_name
	 * @mbggenerated
	 */
	public void setAdderName(String adderName) {
		this.adderName = adderName == null ? null : adderName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column export.add_time
	 * @return  the value of export.add_time
	 * @mbggenerated
	 */
	public Date getAddTime() {
		return addTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column export.add_time
	 * @param addTime  the value for export.add_time
	 * @mbggenerated
	 */
	public void setAddTime(Date addTime) {
		this.addTime = addTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column export.updater_name
	 * @return  the value of export.updater_name
	 * @mbggenerated
	 */
	public String getUpdaterName() {
		return updaterName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column export.updater_name
	 * @param updaterName  the value for export.updater_name
	 * @mbggenerated
	 */
	public void setUpdaterName(String updaterName) {
		this.updaterName = updaterName == null ? null : updaterName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column export.update_time
	 * @return  the value of export.update_time
	 * @mbggenerated
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column export.update_time
	 * @param updateTime  the value for export.update_time
	 * @mbggenerated
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}